[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wagtail-vector-index"
authors = [{name = "Tom Usher", email = "tom@tomusher.com"}]
description = "Add your content to vector indexes for fast search and similarity matching."
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Framework :: Wagtail",
    "Framework :: Wagtail :: 6",
    "Framework :: Wagtail :: 7",
]
dynamic = ["version"]
requires-python = ">=3.11"
dependencies = [
    "Django>=5.0,<5.3",
    "Wagtail>=5.2,<7.0",
    "litellm>=1.58.0",
    "openai>=1.58.0",
    "aiohttp>=3.10.0",
]
[project.optional-dependencies]
numpy = [
    "numpy>=1.26.0,<3.0",
]
pgvector = [
    "pgvector>=0.3.6",
]
qdrant = [
    "qdrant-client>=1.12.0",
]
weaviate = [
    "weaviate-client>=4.9.0",
]
llm = [
    "llm>=0.18",
]
testing = [
    "dj-database-url>=2.3.0",
    "pre-commit>=4.0.0",
    "pytest>=8.3.0",
    "pytest-asyncio>=0.25.0",
    "pytest-mock>=3.14.0",
    "pytest-django>=4.9.0",
    "wagtail-factories>=4.2.0",
    "factory-boy>=3.3.0",
    "coverage>=7.6,<8.0",
    "pyright>=1.1.400",
    "django-types>=0.19.1",
]
docs = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
    "mkdocs-awesome-pages-plugin>=2.10.0"
]

[project.urls]
Home = "https://github.com/wagtail/wagtail-vector-index"

[tool.flit.module]
name = "wagtail_vector_index"

[tool.flit.sdist]
include = [
    "wagtail_vector_index/static"
]
exclude = [
    "wagtail_vector_index/static_src",
    "wagtail_vector_index/test",
    "wagtail_vector_index/static/wagtail_vector_index/js/.gitignore",
    "tests",
    "testmanage.py",
    ".*",
    "*.js",
    "*.json",
    "*.ini",
    "*.yml"
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "testapp.settings"
pythonpath = ["./", "./tests"]
log_level = "INFO"
asyncio_mode = "auto"
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.ruff.lint]
select = ["F", "E", "C90", "I", "B", "DJ", "RUF", "TRY", "C4", "TCH005", "TCH004"]
ignore = ["TRY003", "E501", "RUF012"]

[tool.pyright]
include = ["src/**"]
exclude = [
    "**/migrations",
    "src/wagtail_vector_index/storage/qdrant/provider.py",
]
pythonVersion = "3.11"
typeCheckingMode = "basic"
